### ISSUE TITLE
"automatically check for and install any missing required packages" not working in venv

### ISSUE THREAD

**Issue by acbekoac** [coffinsp/lostools#1]
the "automatically check for and install any missing required packages" iusing xlsninja.py is not working out of the box, some preinstallations are needed

python3 --version       
Python 3.11.9

git clone https://github.com/coffinsp/lostools.git
python3 -m venv lostools
cd lostools
source ./bin/activate

python3 ./xlsNinja.py       
Traceback (most recent call last):
  File "/home/acbeko/git_tools/lostools/./xlsNinja.py", line 27, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'

pip3 install -r requirements.txt

python3 ./xlsNinja.py           
Traceback (most recent call last):
  File "/home/acbeko/git_tools/lostools/./xlsNinja.py", line 34, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'

pip3 install bs4

python3 ./xlsNinja.py
--> now works (installs some packages and gives the "Select an option" prompt

**Comment by acbekoac** [comment]
python --version
Der Befehl 'python' wurde nicht gefunden, meinten Sie:
  Befehl 'python3' aus dem deb python3
  Befehl 'python' aus dem deb python-is-python3


sudo apt install python-is-python3


python --version
Python 3.11.9


git clone https://github.com/coffinsp/lostools.git
python -m venv lostools
cd lostools
source ./bin/activate


python ./xlsNinja.py 
Traceback (most recent call last):
  File "/home/acbeko/git_tools/lostools/./xlsNinja.py", line 27, in <module>
    from colorama import Fore, Style, init
ModuleNotFoundError: No module named 'colorama'


--> still same problem

**Comment by coffinsp** [comment]
pip install colorama

**Comment by acbekoac** [comment]
pip3 install colorama

python xlsNinja.py   
Traceback (most recent call last):
  File "/home/acbeko/git_tools/lostools/xlsNinja.py", line 29, in <module>
    from rich import print as rich_print
ModuleNotFoundError: No module named 'rich'

--> rich is the next package in requirements.txt

as installing the packages in requiremnts.txt and additionaly bs4 (add to this file?) works here,  it's fine for me to add some note on the webpage ;)

**Comment by 0xhunster** [comment]
Hello @acbekoac 

just follow these steps,

```
git clone https://github.com/coffinsp/lostools.git
cd lostools
pip3 install -r requirements.txt
```

Then simply run `python3 xlsNinja.py`

**Comment by psych4cker** [comment]
> Hello @acbekoac
> 
> just follow these steps,
> 
> ```
> git clone https://github.com/coffinsp/lostools.git
> cd lostools
> pip3 install -r requirements.txt
> ```
> 
> Then simply run `python3 xlsNinja.py`

I follow your steps and it is showing me this 
```
  python3 xlsNinja.py
Traceback (most recent call last):
  File "/home/kali/tools/lostools/xlsNinja.py", line 34, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
```

**Comment by coffinsp** [comment]
you need to install bs4 module requirements first
