### ISSUE TITLE
Lots of false postive on SQLi scanner

### ISSUE THREAD

**Issue by jeetpal2007** [coffinsp/lostools#10]
Hey @coffinsp 
I have tested the SQLi scanner and notice that the result is totally different the tools does not managed to detect the SQLi I used your old tools on one of the vulnerable target it detect the SQLi but this scanner can't it give 0 result but the BSQLi tool give 5 please make changes

**Comment by coffinsp** [comment]
bcz its uses urlencoding to encode all payload and show results you can test without urlencoding payload that show while scanning testing with xor.... payload use it without encode and try..
