### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Dark-Aura** [coffinsp/lostools#12]
* **Why did you remove the verbose option? Last week, in your video, I saw that option. If you add that feature here, it will be helpful for us. Please do the needful.**

![telegram-cloud-photo-size-5-6255913453864729862-y](https://github.com/user-attachments/assets/1b060534-612a-4610-910d-cb22cdfaf5e7)

![telegram-cloud-photo-size-5-6255913453864729861-y](https://github.com/user-attachments/assets/b4ce33cb-4a52-4877-aa0b-4fce413ef392)

**Comment by Vointra** [comment]
no bro it's different tools, you can check it at this link: https://github.com/coffinsp/customBsqli
