### ISSUE TITLE
Error with character '?'

### ISSUE THREAD

**Issue by LucasPDiniz** [coffinsp/lostools#14]
Here is causing a problem when there is the character '?' in the URL. If you remove it, it works normally.
Does it happen to anyone else?

URL: http://testphp.vulnweb.com/hpp/?pp=123

![x](https://github.com/user-attachments/assets/0f4fae25-8ad7-43b3-898d-13bca3a146d0)

**Comment by rlsnkali2324** [comment]
works fine in me.
