### ISSUE TITLE
Chrome Error occured in the tool

### ISSUE THREAD

**Issue by Garte153sa** [coffinsp/lostools#21]
Input is 
![Screenshot (232)](https://github.com/user-attachments/assets/6603b1d5-ca83-4b56-b3dc-3ab6420f2ea0)
and next Enter

The Error While running the tool is :
![Screenshot (233)](https://github.com/user-attachments/assets/af38645a-6763-486c-be4c-019867c5ff1f)
![Screenshot (234)](https://github.com/user-attachments/assets/044c566d-d2c1-4686-95bf-67603d5f71ea)
This is the total issue
any help i tried a lot i have done the 'pip3 install -r requirments.txt'
and chrome driver installed

**Comment by Garte153sa** [comment]
I am eagerly waiting to use this tool in my sytem 🤩🤩

**Comment by coffinsp** [comment]
you need to install driver try manually installing..

**Comment by Garte153sa** [comment]
What do you mean chrome drivers i have it

**Comment by Garte153sa** [comment]
bro can u tell how have u connected the Browser of localhost in wsl i understood the error is that chrome is not installed in my wsl

**Comment by Garte153sa** [comment]
And use firefox instead of chrome
