### ISSUE TITLE
Vulnerable URLs for Every Attack Should Be Saved in a Output File

### ISSUE THREAD

**Issue by kalmux1** [coffinsp/lostools#3]
**Description:** _The tool should automatically save all detected vulnerable URLs from SQLi, LFI, XSS, and Open Redirect scans into a file. This will help track vulnerabilities and simplify reporting by keeping a log of the identified URLs for each scan. The file should update after each run, without overwriting previous results._

**Comment by coffinsp** [comment]
it is avaible when scan done it ask for filename to save
